# Generated by Django 4.1.3 on 2022-12-19 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='numero_comision',
            new_name='comision',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='nombre_curso',
            new_name='nombre',
        ),
    ]
